name: Deploy
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      # TODO: add a build step here
      - name: Setup Deno
        uses: denoland/setup-deno@v1.1.0

      - run: deno task build

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "ebiy0rom0-sekareco-develop"
          entrypoint: main.tsx
          root: dist
